/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CKW7ombXiZ8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
// import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
// import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div
      className="min-h-screen bg-gray-100 flex flex-col items-center justify-center">
      <header className="w-full bg-white shadow">
        <div className="container mx-auto flex justify-between items-center p-4">
          <div className="flex items-center space-x-2">
            <img src="/logo.svg" alt="Mensa Capital Logo" className="h-12" />
            <span className="text-2xl font-bold text-gray-800">Mensa Capital</span>
          </div>
          <nav className="space-x-4 flex items-center">
            <a href="#" className="text-gray-700 hover:text-gray-900">
              Home
            </a>
            <a href="#" className="text-gray-700 hover:text-gray-900">
              About
            </a>
            <a href="#" className="text-gray-700 hover:text-gray-900">
              Portfolio
            </a>
            <a href="#" className="text-gray-700 hover:text-gray-900">
              Contact
            </a>
            {/* <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  className="flex items-center gap-1 rounded-xl px-3 h-10 data-[state=open]:bg-muted text-lg">
                  EN <ChevronDownIcon className="w-4 h-4 text-muted-foreground" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-40">
                <DropdownMenuItem className="flex items-center gap-2">
                  <div
                    className="w-5 h-5 flex items-center justify-center rounded-full bg-primary text-primary-foreground">
                    EN
                  </div>
                  English
                </DropdownMenuItem>
                <DropdownMenuItem className="flex items-center gap-2">
                  <div
                    className="w-5 h-5 flex items-center justify-center rounded-full bg-secondary text-secondary-foreground">
                    ES
                  </div>
                  Español
                </DropdownMenuItem>
                <DropdownMenuItem className="flex items-center gap-2">
                  <div
                    className="w-5 h-5 flex items-center justify-center rounded-full bg-accent text-accent-foreground">
                    FR
                  </div>
                  Français
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu> */}
          </nav>
        </div>
      </header>
      <main className="flex-1 container mx-auto p-4">
        <section id="home" className="text-center py-20">
          <h1 className="text-4xl font-bold text-gray-800">Welcome to Mensa Capital</h1>
          <p className="mt-4 text-gray-600">Your trusted partner in crypto venture capital.</p>
        </section>
        <section id="about" className="py-20">
          <h2 className="text-3xl font-bold text-gray-800">About Us</h2>
          <p className="mt-4 text-gray-600">
            Mensa Capital is a leading venture capital firm specializing in cryptocurrency investments. Our mission is
            to empower innovative blockchain projects with the resources and expertise they need to succeed.
          </p>
        </section>
        <section id="portfolio" className="py-20">
          <h2 className="text-3xl font-bold text-gray-800">Our Portfolio</h2>
          <div className="mt-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="bg-white shadow rounded p-4">
              <h3 className="text-xl font-bold text-gray-800">Project A</h3>
              <p className="mt-2 text-gray-600">Description of Project A.</p>
            </div>
            <div className="bg-white shadow rounded p-4">
              <h3 className="text-xl font-bold text-gray-800">Project B</h3>
              <p className="mt-2 text-gray-600">Description of Project B.</p>
            </div>
            <div className="bg-white shadow rounded p-4">
              <h3 className="text-xl font-bold text-gray-800">Project C</h3>
              <p className="mt-2 text-gray-600">Description of Project C.</p>
            </div>
          </div>
        </section>
        <section id="contact" className="py-20">
          <h2 className="text-3xl font-bold text-gray-800">Contact Us</h2>
          <form className="mt-8 space-y-4">
            <div>
              <label htmlFor="name" className="block text-gray-700">
                Name
              </label>
              <input
                type="text"
                id="name"
                className="w-full border-gray-300 rounded mt-1"
                placeholder="Your name" />
            </div>
            <div>
              <label htmlFor="email" className="block text-gray-700">
                Email
              </label>
              <input
                type="email"
                id="email"
                className="w-full border-gray-300 rounded mt-1"
                placeholder="Your email" />
            </div>
            <div>
              <label htmlFor="message" className="block text-gray-700">
                Message
              </label>
              <textarea
                id="message"
                className="w-full border-gray-300 rounded mt-1"
                placeholder="Your message" />
            </div>
            <button type="submit" className="bg-blue-600 text-white px-4 py-2 rounded">
              Send Message
            </button>
          </form>
        </section>
      </main>
      <footer className="w-full bg-gray-800 text-white py-4">
        <div className="container mx-auto text-center">&copy; 2023 Mensa Capital. All rights reserved.</div>
      </footer>
    </div>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
